// EcoCitizen Mock Data Schemas (as specified in EcoCitizen_Frontend_PRD_Antigravity.md)

export const MOCK_ISSUES = [
  {
    id: "101",
    title: "Toxic Slag & Heavy Plastic Runoff near Willow Creek",
    category: "Water Contamination",
    location: "Willow Creek Greenway, North Bank",
    coordinates: [37.7749, -122.4194],
    status: "In Progress",
    urgency: "High", // High = Red / Alert Orange, Medium = Yellow, Low = Green
    upvotes: 42,
    hasUpvoted: false,
    imageUrl: "https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=800&q=80",
    resolvedImageUrl: null,
    timestamp: "2 Hours ago",
    description: "Significant industrial effluent creating opaque blue foam and chemical odors drifting into the salmon spawning habitat. Downstream water clarity critically degraded.",
    reportedBy: "Elena Rostova"
  },
  {
    id: "102",
    title: "Illegal E-Waste & Battery Dumping in Oakridge Park",
    category: "Waste Management",
    location: "Oakridge Park, South Trailhead",
    coordinates: [37.7650, -122.4450],
    status: "Pending",
    urgency: "High",
    upvotes: 28,
    hasUpvoted: false,
    imageUrl: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80",
    resolvedImageUrl: null,
    timestamp: "4 Hours ago",
    description: "Over 30 discarded lead-acid batteries and stripped circuit boards dumped under pine grove. Imminent rain may cause heavy metal leaching into soil.",
    reportedBy: "Marcus Chen"
  },
  {
    id: "103",
    title: "Unauthorized Heritage Tree Cutting behind Industrial Zone",
    category: "Deforestation",
    location: "Bayshore Industrial Perimeter",
    coordinates: [37.7520, -122.3980],
    status: "Pending",
    urgency: "Medium",
    upvotes: 19,
    hasUpvoted: false,
    imageUrl: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80",
    resolvedImageUrl: null,
    timestamp: "1 Day ago",
    description: "Contractors bulldozing mature eucalyptus and live oak trees outside designated zoning lines. No municipal permit displayed on fence.",
    reportedBy: "Sarah Lin"
  },
  {
    id: "104",
    title: "Dense Diesel Soot & Chemical Plume from Pier Exhaust",
    category: "Air Pollution",
    location: "Harbor Logistics District, Pier 18",
    coordinates: [37.7880, -122.3890],
    status: "In Progress",
    urgency: "Medium",
    upvotes: 35,
    hasUpvoted: true,
    imageUrl: "https://images.unsplash.com/photo-1569163139599-0f4517e36f51?auto=format&fit=crop&w=800&q=80",
    resolvedImageUrl: null,
    timestamp: "2 Days ago",
    description: "Heavy black exhaust plume discharging constantly during evening hours. Pungent chemical odor spreading into adjacent residential neighborhood.",
    reportedBy: "Kavita Patel"
  },
  {
    id: "105",
    title: "Cleared Plastic Debris & Restored Lagoon Bank",
    category: "Water Contamination",
    location: "Marina Harbor Lagoon",
    coordinates: [37.8050, -122.4350],
    status: "Resolved",
    urgency: "Low",
    upvotes: 67,
    hasUpvoted: true,
    imageUrl: "https://images.unsplash.com/photo-1621451537084-482c73073a0f?auto=format&fit=crop&w=800&q=80",
    resolvedImageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    timestamp: "3 Days ago",
    description: "Over 400 lbs of floating single-use packaging and debris remediated. Netting filter successfully installed at storm drain inlet.",
    reportedBy: "David Romero"
  },
  {
    id: "106",
    title: "Deep Roadway Sinkhole & Fractured Storm Culvert",
    category: "Potholes & Hazards",
    location: "Potrero Hill, 17th & Connecticut",
    coordinates: [37.7630, -122.3950],
    status: "In Progress",
    urgency: "High",
    upvotes: 51,
    hasUpvoted: false,
    imageUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80",
    resolvedImageUrl: null,
    timestamp: "1 Day ago",
    description: "3-foot wide cave-in exposing ruptured culvert. Water pooling rapidly during light rain, endangering bicycles and passing vehicles.",
    reportedBy: "Chaitanya Anand"
  },
  {
    id: "107",
    title: "Overflowing Commercial Dumpster Damaging Wetland Buffer",
    category: "Waste Management",
    location: "Presidio Marsh Edge, East Gate",
    coordinates: [37.8010, -122.4680],
    status: "Resolved",
    urgency: "Low",
    upvotes: 38,
    hasUpvoted: false,
    imageUrl: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80",
    resolvedImageUrl: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80",
    timestamp: "4 Days ago",
    description: "Uncontained refuse blowing into sensitive coastal bird nesting areas. Remediated and replaced with tamper-proof wildlife bins.",
    reportedBy: "Dr. Jesse Wong"
  }
];

export const MOCK_INITIATIVES = [
  {
    id: "INIT-201",
    title: "The Great Urban Canopy Blitz",
    category: "Urban Reforestation",
    description: "Revitalizing urban heat corridors by planting 500 climate-resilient native saplings equipped with smart soil moisture tags.",
    organizer: "Green City Coalition & Urban Forestry",
    location: "District 7 Greenways & School Corridors",
    date: "Saturday, Oct 3, 2026 • 09:00 AM",
    volunteersRegistered: 45,
    volunteersTarget: 50,
    imageUrl: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80",
    hasJoined: true,
    ecoPointsReward: 50
  },
  {
    id: "INIT-202",
    title: "River & Coastal Plastic Interceptor Drive",
    category: "Clean Water",
    description: "Community cleanup squad using kayaks and magnetic rakes to intercept floating debris before it reaches the bay marine sanctuary.",
    organizer: "Clean Waters Alliance & Baykeepers",
    location: "Estuary Marina & South Pier",
    date: "Sunday, Oct 11, 2026 • 08:30 AM",
    volunteersRegistered: 38,
    volunteersTarget: 60,
    imageUrl: "https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&w=800&q=80",
    hasJoined: false,
    ecoPointsReward: 40
  },
  {
    id: "INIT-203",
    title: "Neighborhood Rooftop Solar Co-op Pilot",
    category: "Clean Energy",
    description: "Pooling neighborhood purchasing power to equip 25 low-income homes with solar PV panels and battery storage backups.",
    organizer: "Citizen Power Network",
    location: "Mission Valley Civic Hall",
    date: "Saturday, Oct 17, 2026 • 10:00 AM",
    volunteersRegistered: 21,
    volunteersTarget: 25,
    imageUrl: "https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80",
    hasJoined: false,
    ecoPointsReward: 60
  },
  {
    id: "INIT-204",
    title: "Hazardous E-Waste & Rare Metal Recycling Sprint",
    category: "Circular Economy",
    description: "Safely collect and process obsolete computers, cell phones, and lithium batteries to prevent toxic soil contamination.",
    organizer: "Zero Waste Vanguard",
    location: "Civic Plaza Central Hub",
    date: "Saturday, Oct 24, 2026 • 09:00 AM",
    volunteersRegistered: 62,
    volunteersTarget: 80,
    imageUrl: "https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=800&q=80",
    hasJoined: false,
    ecoPointsReward: 35
  },
  {
    id: "INIT-205",
    title: "Native Pollinator Highway & Pocket Meadow",
    category: "Biodiversity",
    description: "Transforming barren median strips into drought-tolerant milkweed and wildflower sanctuaries for monarch butterflies and native bees.",
    organizer: "Wild Pollinators Guild",
    location: "Boulevard Median Corridors",
    date: "Sunday, Nov 1, 2026 • 09:30 AM",
    volunteersRegistered: 34,
    volunteersTarget: 40,
    imageUrl: "https://images.unsplash.com/photo-1470240731273-7821a6eeb6bd?auto=format&fit=crop&w=800&q=80",
    hasJoined: false,
    ecoPointsReward: 45
  }
];

export const MOCK_USER = {
  name: "Chaitanya Anand",
  handle: "@chaitanya_eco",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
  rankTitle: "Level 3: Green Guardian",
  tierLevel: 3,
  ecoPoints: 485,
  nextLevelPoints: 600,
  issuesReported: 8,
  issuesResolved: 7,
  initiativesJoined: 3,
  badges: [
    { id: "first_responder", name: "First Responder", desc: "Reported an environmental hazard within 1 hr of occurrence", icon: "zap", unlocked: true },
    { id: "canopy_defender", name: "Canopy Defender", desc: "Participated in native tree planting drives", icon: "trees", unlocked: true },
    { id: "water_sentinel", name: "Clean Water Sentinel", desc: "Flagged industrial runoff in local waterways", icon: "droplets", unlocked: true },
    { id: "zero_waste_hero", name: "Zero-Waste Titan", desc: "Collected over 50kg of recyclable e-waste", icon: "recycle", unlocked: true },
    { id: "community_voice", name: "Civic Mobilizer", desc: "Upvoted and verified 25+ citizen environmental reports", icon: "users", unlocked: false }
  ]
};
